# Generated by Django 3.2.5 on 2021-08-24 11:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210824_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
