# Generated by Django 3.2.5 on 2021-08-24 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_keyword_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.story'),
        ),
    ]
