# Generated by Django 3.2.5 on 2021-08-24 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_key_keyword_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyword',
            name='title',
        ),
    ]
