# Generated by Django 3.2.5 on 2021-08-25 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_keyword_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='keyword',
        ),
    ]
